import '../shape/shape.dart';
import 'level.dart';

/// Shorthand for authoring: parse a shape from the DSL in [Shape].
Shape _s(String dsl) => Shape.parse(dsl);

const _rotate = RotateMove();
const _cut = CutMove();
StackMove _place(String dsl) => StackMove(dsl);
PaintMove _paint(QuadColor color) => PaintMove(color);

/// The shipped puzzle set.
///
/// The ramp introduces exactly one idea at a time: rotate, place, paint, layer
/// order, cut, then the combinations. Because paint always covers the whole
/// board, multi-coloured goals force the player to build a colour, cut it aside
/// and reassemble - that tension is what the back half of the game is about.
final List<Level> kLevels = [
  Level(
    number: 1,
    name: 'First Turn',
    brief: 'Rotate the plate a quarter turn clockwise.',
    start: _s('Cu/-/-/-'),
    goal: _s('-/Cu/-/-'),
    canRotate: true,
    solution: const [_rotate],
  ),
  Level(
    number: 2,
    name: 'Two Turns',
    brief: 'Everything on the plate turns together.',
    start: _s('Cu/Su/-/-'),
    goal: _s('-/-/Su/Cu'),
    canRotate: true,
    solution: const [_rotate, _rotate],
  ),
  Level(
    number: 3,
    name: 'Drop In',
    brief: 'Drag a blueprint from the tray onto the plate.',
    goal: _s('Cu/Cu/-/-'),
    tray: [_s('Cu/-/-/-'), _s('-/Cu/-/-')],
    solution: [_place('Cu/-/-/-'), _place('-/Cu/-/-')],
  ),
  Level(
    number: 4,
    name: 'Fresh Coat',
    brief: 'Drop a colour to paint the whole plate at once.',
    goal: _s('Sr/Sr/Sr/Sr'),
    tray: [_s('Su/Su/Su/Su')],
    colors: const [QuadColor.red],
    solution: [_place('Su/Su/Su/Su'), _paint(QuadColor.red)],
  ),
  Level(
    number: 5,
    name: 'Underneath',
    brief: 'A dropped piece slides under what is already there.',
    goal: _s('Su+Cu/-/-/-'),
    tray: [_s('Cu/-/-/-'), _s('Su/-/-/-')],
    solution: [_place('Cu/-/-/-'), _place('Su/-/-/-')],
  ),
  Level(
    number: 6,
    name: 'Corner Pair',
    brief: 'Place, turn, place again.',
    goal: _s('Cu/Su/-/-'),
    tray: [_s('Cu/-/-/-'), _s('Su/-/-/-')],
    canRotate: true,
    solution: [_place('Su/-/-/-'), _rotate, _place('Cu/-/-/-')],
  ),
  Level(
    number: 7,
    name: 'Pinwheel',
    brief: 'One blueprint, four quadrants.',
    goal: _s('Cu/Cu/Cu/Cu'),
    tray: [_s('Cu/-/-/-')],
    canRotate: true,
    solution: [
      _place('Cu/-/-/-'),
      _rotate,
      _place('Cu/-/-/-'),
      _rotate,
      _place('Cu/-/-/-'),
      _rotate,
      _place('Cu/-/-/-'),
    ],
  ),
  Level(
    number: 8,
    name: 'Slice',
    brief: 'Cutting splits the plate in two and keeps both halves.',
    goal: _s('Cu/Cu/-/-'),
    tray: [_s('Cu/Cu/Cu/Cu')],
    canCut: true,
    solution: [_place('Cu/Cu/Cu/Cu'), _cut, _place('Cu/Cu/-/-')],
  ),
  Level(
    number: 9,
    name: 'Right Column',
    brief: 'Cut halves keep their row. Turning moves them.',
    goal: _s('-/Su/-/Su'),
    tray: [_s('Su/Su/Su/Su')],
    canRotate: true,
    canCut: true,
    solution: [_place('Su/Su/Su/Su'), _cut, _place('Su/Su/-/-'), _rotate],
  ),
  Level(
    number: 10,
    name: 'Ring Stack',
    brief: 'Three pieces, one quadrant, outside in.',
    goal: _s('Tu+Su+Cu/-/-/-'),
    tray: [_s('Cu/-/-/-'), _s('Su/-/-/-'), _s('Tu/-/-/-')],
    solution: [_place('Cu/-/-/-'), _place('Su/-/-/-'), _place('Tu/-/-/-')],
  ),
  Level(
    number: 11,
    name: 'Green Base',
    brief: 'Turn the pair down, then build on top of it.',
    goal: _s('-/-/Cg+Wg/Cg+Wg'),
    tray: [_s('Wu/Wu/-/-'), _s('-/-/Cu/Cu')],
    colors: const [QuadColor.green],
    canRotate: true,
    solution: [
      _place('Wu/Wu/-/-'),
      _rotate,
      _rotate,
      _place('-/-/Cu/Cu'),
      _paint(QuadColor.green),
    ],
  ),
  Level(
    number: 12,
    name: 'Two Tones',
    brief: 'Paint covers everything, so bank a colour before mixing.',
    goal: _s('Cr/Cr/Cb/Cb'),
    tray: [_s('Cu/Cu/Cu/Cu')],
    colors: const [QuadColor.red, QuadColor.blue],
    canCut: true,
    solution: [
      _place('Cu/Cu/Cu/Cu'),
      _paint(QuadColor.red),
      _cut,
      _place('Cu/Cu/Cu/Cu'),
      _paint(QuadColor.blue),
      _cut,
      _place('Cr/Cr/-/-'),
      _place('-/-/Cb/Cb'),
    ],
  ),
  Level(
    number: 13,
    name: 'Alternating',
    brief: 'Plan the turns backwards from the last piece you place.',
    goal: _s('Su/Cu/Su/Cu'),
    tray: [_s('Cu/-/-/-'), _s('Su/-/-/-')],
    canRotate: true,
    solution: [
      _place('Su/-/-/-'),
      _rotate,
      _place('Cu/-/-/-'),
      _rotate,
      _place('Cu/-/-/-'),
      _rotate,
      _place('Su/-/-/-'),
    ],
  ),
  Level(
    number: 14,
    name: 'Layer Cake',
    brief: 'Four layers is the limit for one quadrant.',
    goal: _s('Wu+Tu+Su+Cu/-/-/-'),
    tray: [_s('Cu/-/-/-'), _s('Su/-/-/-'), _s('Tu/-/-/-'), _s('Wu/-/-/-')],
    solution: [
      _place('Cu/-/-/-'),
      _place('Su/-/-/-'),
      _place('Tu/-/-/-'),
      _place('Wu/-/-/-'),
    ],
  ),
  Level(
    number: 15,
    name: 'Split Tint',
    brief: 'Two colours can share one stack if you bank them first.',
    goal: _s('Cb+Cr/Cb+Cr/-/-'),
    tray: [_s('Cu/Cu/-/-')],
    colors: const [QuadColor.red, QuadColor.blue],
    canCut: true,
    solution: [
      _place('Cu/Cu/-/-'),
      _paint(QuadColor.red),
      _cut,
      _place('Cu/Cu/-/-'),
      _paint(QuadColor.blue),
      _cut,
      _place('Cr/Cr/-/-'),
      _place('Cb/Cb/-/-'),
    ],
  ),
  Level(
    number: 16,
    name: 'Double Glaze',
    brief: 'Bank the inner colour, then glaze the shell.',
    goal: _s('Sc+Cp/Sc+Cp/Sc+Cp/Sc+Cp'),
    tray: [_s('Cu/Cu/Cu/Cu'), _s('Su/Su/Su/Su')],
    colors: const [QuadColor.purple, QuadColor.cyan],
    canCut: true,
    solution: [
      _place('Su/Su/Su/Su'),
      _paint(QuadColor.cyan),
      _cut,
      _place('Cu/Cu/Cu/Cu'),
      _paint(QuadColor.purple),
      _place('Sc/Sc/-/-'),
      _place('-/-/Sc/Sc'),
    ],
  ),
  Level(
    number: 17,
    name: 'Isolate',
    brief: 'A single quadrant can only be banked from a single quadrant.',
    goal: _s('Wy/Wr/-/-'),
    tray: [_s('Wu/-/-/-')],
    colors: const [QuadColor.red, QuadColor.yellow],
    canRotate: true,
    canCut: true,
    solution: [
      _place('Wu/-/-/-'),
      _paint(QuadColor.red),
      _cut,
      _place('Wu/-/-/-'),
      _paint(QuadColor.yellow),
      _cut,
      _place('Wr/-/-/-'),
      _rotate,
      _place('Wy/-/-/-'),
    ],
  ),
  Level(
    number: 18,
    name: 'Grand Design',
    brief: 'Everything at once. Take your time.',
    goal: _s('Cr/Cb/Cr/Cb'),
    tray: [_s('Cu/-/-/-')],
    colors: const [QuadColor.red, QuadColor.blue],
    canRotate: true,
    canCut: true,
    solution: [
      _place('Cu/-/-/-'),
      _paint(QuadColor.red),
      _cut,
      _place('Cu/-/-/-'),
      _paint(QuadColor.blue),
      _cut,
      _place('Cr/-/-/-'),
      _rotate,
      _place('Cb/-/-/-'),
      _rotate,
      _place('Cb/-/-/-'),
      _rotate,
      _place('Cr/-/-/-'),
    ],
  ),
];

Level levelByNumber(int number) =>
    kLevels.firstWhere((l) => l.number == number, orElse: () => kLevels.first);
