import '../shape/shape.dart';
import 'level.dart';

/// Shorthand for authoring: parse a shape from the DSL in [Shape].
Shape _s(String dsl) => Shape.parse(dsl);

const _rotate = RotateMove();
const _cut = CutMove();
StackMove _place(String dsl) => StackMove(dsl);
PaintMove _paint(QuadColor color) => PaintMove(color);

/// Shipped puzzle set, ordered for progressive unlock.
///
/// Tutorial sections teach one verb at a time. After that, each world is a
/// handful of distinct puzzles — not a shape intro ramp — and reference lines
/// get longer by section. Many start with a piece already on the plate: bank
/// it, unfuse it, or park it before paint can ruin it.
final List<Level> kLevels = [
  // ── Tutorial · Turn ──
  Level(
    number: 1,
    name: 'First Turn',
    section: 'Tutorial · Turn',
    brief: 'A quarter-turn clockwise — like a key in a lock.',
    start: _s('Cu/-/-/-'),
    goal: _s('-/Cu/-/-'),
    canRotate: true,
    solution: const [_rotate],
  ),
  Level(
    number: 2,
    name: 'In Step',
    section: 'Tutorial · Turn',
    brief: 'What sits together, spins together.',
    start: _s('Cu/Su/-/-'),
    goal: _s('-/-/Su/Cu'),
    canRotate: true,
    solution: const [_rotate, _rotate],
  ),
  Level(
    number: 3,
    name: 'The Long Way',
    section: 'Tutorial · Turn',
    brief: 'Three clicks walk a piece the long way home.',
    start: _s('Su/-/-/-'),
    goal: _s('-/-/Su/-'),
    canRotate: true,
    solution: const [_rotate, _rotate, _rotate],
  ),
  // ── Tutorial · Place ──
  Level(
    number: 4,
    name: 'First Drop',
    section: 'Tutorial · Place',
    brief: 'A plan in the tray is a piece on the plate.',
    goal: _s('Cu/-/-/-'),
    tray: [_s('Cu/-/-/-')],
    solution: [_place('Cu/-/-/-')],
  ),
  Level(
    number: 5,
    name: 'Two Parts',
    section: 'Tutorial · Place',
    brief: 'Two plans, two corners. Both belong.',
    goal: _s('Cu/Su/-/-'),
    tray: [_s('Cu/-/-/-'), _s('-/Su/-/-')],
    solution: [_place('Cu/-/-/-'), _place('-/Su/-/-')],
  ),
  Level(
    number: 6,
    name: 'Across',
    section: 'Tutorial · Place',
    brief: 'Some plans stretch across a pair of corners.',
    goal: _s('Su/Su/-/-'),
    tray: [_s('Su/Su/-/-')],
    solution: [_place('Su/Su/-/-')],
  ),
  // ── Tutorial · Turn + Place ──
  Level(
    number: 7,
    name: 'Park It',
    section: 'Tutorial · Turn + Place',
    brief: 'Drop it, then stroll it into the empty stall.',
    goal: _s('-/Su/-/-'),
    tray: [_s('Su/-/-/-')],
    canRotate: true,
    solution: [_place('Su/-/-/-'), _rotate],
  ),
  Level(
    number: 8,
    name: 'Three Corners',
    section: 'Tutorial · Turn + Place',
    brief: 'Place, turn, place — a little waltz around the plate.',
    goal: _s('Cu/Cu/-/Cu'),
    tray: [_s('Cu/-/-/-')],
    canRotate: true,
    solution: [
      _place('Cu/-/-/-'),
      _rotate,
      _place('Cu/-/-/-'),
      _rotate,
      _place('Cu/-/-/-'),
    ],
  ),
  Level(
    number: 9,
    name: 'Chequer',
    section: 'Tutorial · Turn + Place',
    brief: 'Dark, light, dark, light. Turn between the notes.',
    goal: _s('Su/Cu/Su/Cu'),
    tray: [_s('Cu/-/-/-'), _s('Su/-/-/-')],
    canRotate: true,
    solution: [
      _place('Su/-/-/-'),
      _rotate,
      _place('Cu/-/-/-'),
      _rotate,
      _place('Cu/-/-/-'),
      _rotate,
      _place('Su/-/-/-'),
    ],
  ),
  // ── Tutorial · Stack ──
  Level(
    number: 10,
    name: 'Underneath',
    section: 'Tutorial · Stack',
    brief: 'Newcomers slip under the ones already seated.',
    goal: _s('Su+Cu/-/-/-'),
    tray: [_s('Cu/-/-/-'), _s('Su/-/-/-')],
    solution: [_place('Cu/-/-/-'), _place('Su/-/-/-')],
  ),
  Level(
    number: 11,
    name: 'Three Deep',
    section: 'Tutorial · Stack',
    brief: 'Biggest at the bottom. Dress from the inside out.',
    goal: _s('Tu+Su+Cu/-/-/-'),
    tray: [_s('Cu/-/-/-'), _s('Su/-/-/-'), _s('Tu/-/-/-')],
    solution: [_place('Cu/-/-/-'), _place('Su/-/-/-'), _place('Tu/-/-/-')],
  ),
  Level(
    number: 12,
    name: 'The Limit',
    section: 'Tutorial · Stack',
    brief: 'Four deep. A corner\'s closet is not endless.',
    goal: _s('Wu+Tu+Su+Cu/-/-/-'),
    tray: [_s('Cu/-/-/-'), _s('Su/-/-/-'), _s('Tu/-/-/-'), _s('Wu/-/-/-')],
    solution: [
      _place('Cu/-/-/-'),
      _place('Su/-/-/-'),
      _place('Tu/-/-/-'),
      _place('Wu/-/-/-'),
    ],
  ),
  // ── Tutorial · Paint ──
  Level(
    number: 13,
    name: 'Fresh Coat',
    section: 'Tutorial · Paint',
    brief: 'One tap of colour floods the whole plate.',
    goal: _s('Sr/Sr/Sr/Sr'),
    tray: [_s('Su/Su/Su/Su')],
    colors: const [QuadColor.red],
    solution: [_place('Su/Su/Su/Su'), _paint(QuadColor.red)],
  ),
  Level(
    number: 14,
    name: 'Blue Bar',
    section: 'Tutorial · Paint',
    brief: 'Shape first. Colour after.',
    goal: _s('Cb/Cb/-/-'),
    tray: [_s('Cu/Cu/-/-')],
    colors: const [QuadColor.blue],
    solution: [_place('Cu/Cu/-/-'), _paint(QuadColor.blue)],
  ),
  Level(
    number: 15,
    name: 'Dyed Stack',
    section: 'Tutorial · Paint',
    brief: 'Paint is no respecter of layers.',
    goal: _s('Sr+Cr/-/-/-'),
    tray: [_s('Cu/-/-/-'), _s('Su/-/-/-')],
    colors: const [QuadColor.red],
    solution: [_place('Cu/-/-/-'), _place('Su/-/-/-'), _paint(QuadColor.red)],
  ),
  // ── Tutorial · Cut ──
  Level(
    number: 16,
    name: 'Slice',
    section: 'Tutorial · Cut',
    brief: 'A cut makes two keepable halves. Nothing is lost.',
    goal: _s('Cu/Cu/-/-'),
    tray: [_s('Cu/Cu/Cu/Cu')],
    canCut: true,
    solution: [_place('Cu/Cu/Cu/Cu'), _cut, _place('Cu/Cu/-/-')],
  ),
  Level(
    number: 17,
    name: 'Stand Up',
    section: 'Tutorial · Cut',
    brief: 'A row, stood on end, becomes a column.',
    goal: _s('-/Su/-/Su'),
    tray: [_s('Su/Su/Su/Su')],
    canRotate: true,
    canCut: true,
    solution: [_place('Su/Su/Su/Su'), _cut, _place('Su/Su/-/-'), _rotate],
  ),
  Level(
    number: 18,
    name: 'Other Half',
    section: 'Tutorial · Cut',
    brief: 'The other half waits. Bring it home on its own.',
    goal: _s('-/-/Cu/Cu'),
    tray: [_s('Cu/Cu/Cu/Cu')],
    canCut: true,
    solution: [_place('Cu/Cu/Cu/Cu'), _cut, _place('-/-/Cu/Cu')],
  ),
  // ── Tutorial · Colour Bank ──
  Level(
    number: 19,
    name: 'Two Tones',
    section: 'Tutorial · Colour Bank',
    brief: 'The brush is greedy. Hide a colour before it drinks.',
    goal: _s('Cr/Cr/Cb/Cb'),
    tray: [_s('Cu/Cu/Cu/Cu')],
    colors: const [QuadColor.red, QuadColor.blue],
    canCut: true,
    solution: [
      _place('Cu/Cu/Cu/Cu'),
      _paint(QuadColor.red),
      _cut,
      _place('Cu/Cu/Cu/Cu'),
      _paint(QuadColor.blue),
      _cut,
      _place('Cr/Cr/-/-'),
      _place('-/-/Cb/Cb'),
    ],
  ),
  Level(
    number: 20,
    name: 'Coloured Core',
    section: 'Tutorial · Colour Bank',
    brief: 'Dye them apart, then let one wear the other.',
    goal: _s('Cb+Cr/Cb+Cr/-/-'),
    tray: [_s('Cu/Cu/-/-')],
    colors: const [QuadColor.red, QuadColor.blue],
    canCut: true,
    solution: [
      _place('Cu/Cu/-/-'),
      _paint(QuadColor.red),
      _cut,
      _place('Cu/Cu/-/-'),
      _paint(QuadColor.blue),
      _cut,
      _place('Cr/Cr/-/-'),
      _place('Cb/Cb/-/-'),
    ],
  ),
  Level(
    number: 21,
    name: 'Corner Dyes',
    section: 'Tutorial · Colour Bank',
    brief: 'One corner at a time. Park the first before the next.',
    goal: _s('Cr/Cy/-/-'),
    tray: [_s('Cu/-/-/-')],
    colors: const [QuadColor.red, QuadColor.yellow],
    canRotate: true,
    canCut: true,
    solution: [
      _place('Cu/-/-/-'),
      _paint(QuadColor.yellow),
      _cut,
      _place('Cu/-/-/-'),
      _paint(QuadColor.red),
      _cut,
      _place('Cy/-/-/-'),
      _rotate,
      _place('Cr/-/-/-'),
    ],
  ),
  // ── Salvage ──
  // The plate is stock. Cut to bank, unfuse, or park before paint can ruin it.
  Level(
    number: 22,
    name: 'Unfuse',
    section: 'Salvage',
    brief: 'Two friends fused at the shoulder. Uncouple them kindly.',
    start: _s('Cu/Su/-/-'),
    goal: _s('Su/Cu/-/-'),
    canRotate: true,
    canCut: true,
    solution: [
      _rotate,
      _cut,
      _place('-/-/-/Su'),
      _rotate,
      _rotate,
      _place('-/Cu/-/-'),
    ],
  ),
  Level(
    number: 23,
    name: 'Bank the Red',
    section: 'Salvage',
    brief: 'Some reds are born, not painted. Mind the next weather.',
    start: _s('Cr/-/-/-'),
    goal: _s('Cr/Cb/-/-'),
    tray: [_s('Cu/-/-/-')],
    colors: const [QuadColor.blue],
    canRotate: true,
    canCut: true,
    solution: [
      _cut,
      _place('Cu/-/-/-'),
      _paint(QuadColor.blue),
      _cut,
      _place('Cb/-/-/-'),
      _rotate,
      _place('Cr/-/-/-'),
    ],
  ),
  Level(
    number: 24,
    name: 'Foundation',
    section: 'Salvage',
    brief: 'A blue floor already laid. Don\'t drown it in a new coat.',
    start: _s('-/-/Sb/Sb'),
    goal: _s('So/So/Sb/Sb'),
    tray: [_s('Su/-/-/-')],
    colors: const [QuadColor.orange],
    canRotate: true,
    canCut: true,
    solution: [
      _cut,
      _place('Su/-/-/-'),
      _paint(QuadColor.orange),
      _cut,
      _place('So/-/-/-'),
      _rotate,
      _place('So/-/-/-'),
      _place('-/-/Sb/Sb'),
    ],
  ),
  Level(
    number: 25,
    name: 'Isolate',
    section: 'Salvage',
    brief: 'Green for the upper room. Let the cellar sleep.',
    start: _s('Cu/Cu/Su/Su'),
    goal: _s('Cg/Cg/Su/Su'),
    colors: const [QuadColor.green],
    canCut: true,
    solution: [
      _cut,
      _place('Cu/Cu/-/-'),
      _paint(QuadColor.green),
      _cut,
      _place('-/-/Su/Su'),
      _place('Cg/Cg/-/-'),
    ],
  ),
  Level(
    number: 26,
    name: 'Under the Star',
    section: 'Salvage',
    brief: 'Gold likes the outer air. Tuck it last, then take a walk.',
    start: _s('Ty/-/-/-'),
    goal: _s('-/-/-/Ty+Su+Cu'),
    tray: [_s('Cu/-/-/-'), _s('Su/-/-/-')],
    canRotate: true,
    canCut: true,
    solution: [
      _cut,
      _place('Cu/-/-/-'),
      _place('Su/-/-/-'),
      _place('Ty/-/-/-'),
      _rotate,
      _rotate,
    ],
  ),
  Level(
    number: 27,
    name: 'Opposites',
    section: 'Salvage',
    brief: 'A pair won\'t stretch to opposite corners. Undo the handshake.',
    start: _s('Cu/Cu/Cu/Cu'),
    goal: _s('Cu/-/-/Cu'),
    canRotate: true,
    canCut: true,
    solution: [
      _cut,
      _place('Cu/Cu/-/-'),
      _rotate,
      _cut,
      _place('-/Cu/-/-'),
      _rotate,
      _rotate,
      _rotate,
      _place('-/-/-/Cu'),
    ],
  ),
  Level(
    number: 28,
    name: 'Park the Mill',
    section: 'Salvage',
    brief: 'Walk the mill, then raise a warmer house around it.',
    start: _s('-/Wu/-/-'),
    goal: _s('Cr/Cr/Wu/-'),
    tray: [_s('Cu/Cu/-/-')],
    colors: const [QuadColor.red],
    canRotate: true,
    canCut: true,
    solution: [
      _rotate,
      _rotate,
      _cut,
      _place('Cu/Cu/-/-'),
      _paint(QuadColor.red),
      _cut,
      _place('-/-/Wu/-'),
      _place('Cr/Cr/-/-'),
    ],
  ),

  // ── Preserve ──
  // Gifts already on the plate must survive. Dye everything else off-board.
  Level(
    number: 29,
    name: 'Two-Tone Moon',
    section: 'Preserve',
    brief: 'One plate, two climates. Split the day from the night.',
    start: _s('Cu/Cu/Cu/Cu'),
    goal: _s('Co/Co/Cc/Cc'),
    colors: const [QuadColor.orange, QuadColor.cyan],
    canCut: true,
    solution: [
      _cut,
      _place('Cu/Cu/-/-'),
      _paint(QuadColor.orange),
      _cut,
      _place('-/-/Cu/Cu'),
      _paint(QuadColor.cyan),
      _cut,
      _place('Co/Co/-/-'),
      _place('-/-/Cc/Cc'),
    ],
  ),
  Level(
    number: 30,
    name: 'Keep the Nest',
    section: 'Preserve',
    brief: 'A yellow heart, already beating. Don\'t drown it.',
    start: _s('Cy/-/-/-'),
    goal: _s('-/-/Cr+Cy/-'),
    tray: [_s('Cu/-/-/-')],
    colors: const [QuadColor.red],
    canRotate: true,
    canCut: true,
    solution: [
      _cut,
      _place('Cu/-/-/-'),
      _paint(QuadColor.red),
      _cut,
      _place('Cy/-/-/-'),
      _place('Cr/-/-/-'),
      _rotate,
      _rotate,
      _rotate,
    ],
  ),
  Level(
    number: 31,
    name: 'Gift Pair',
    section: 'Preserve',
    brief: 'A couple already dressed. Don\'t unpick them for the blue.',
    start: _s('Cr/Cy/-/-'),
    goal: _s('Cr/Cy/Cb/Cb'),
    tray: [_s('Cu/-/-/-')],
    colors: const [QuadColor.blue],
    canRotate: true,
    canCut: true,
    solution: [
      _cut,
      _place('Cu/-/-/-'),
      _paint(QuadColor.blue),
      _cut,
      _place('Cb/-/-/-'),
      _rotate,
      _place('Cb/-/-/-'),
      _rotate,
      _rotate,
      _place('Cr/Cy/-/-'),
    ],
  ),
  Level(
    number: 32,
    name: 'Blade Chequer',
    section: 'Preserve',
    brief: 'Keep the magenta coin. Let the blades learn a warmer song.',
    start: _s('Cm/-/-/-'),
    goal: _s('Po/Cm/Po/Cm'),
    tray: [_s('Pu/-/-/-')],
    colors: const [QuadColor.orange],
    canRotate: true,
    canCut: true,
    solution: [
      _cut,
      _place('Pu/-/-/-'),
      _paint(QuadColor.orange),
      _cut,
      _place('Po/-/-/-'),
      _rotate,
      _place('Cm/-/-/-'),
      _rotate,
      _place('Cm/-/-/-'),
      _rotate,
      _place('Po/-/-/-'),
    ],
  ),
  Level(
    number: 33,
    name: 'Red Foot',
    section: 'Preserve',
    brief: 'Walk the square home. Dye the lintel somewhere quieter.',
    start: _s('Su/-/-/-'),
    goal: _s('Cr/Cr/Su/-'),
    tray: [_s('Cu/Cu/-/-')],
    colors: const [QuadColor.red],
    canRotate: true,
    canCut: true,
    solution: [
      _rotate,
      _rotate,
      _rotate,
      _cut,
      _place('Cu/Cu/-/-'),
      _paint(QuadColor.red),
      _cut,
      _place('-/-/Su/-'),
      _place('Cr/Cr/-/-'),
    ],
  ),
  Level(
    number: 34,
    name: 'Primaries Gift',
    section: 'Preserve',
    brief: 'Red is a guest. Mix the other primaries offstage.',
    start: _s('Cr/-/-/-'),
    goal: _s('Cr/Cb/-/Cg'),
    tray: [_s('Cu/-/-/-')],
    colors: const [QuadColor.blue, QuadColor.green],
    canRotate: true,
    canCut: true,
    solution: [
      _cut,
      _place('Cu/-/-/-'),
      _paint(QuadColor.green),
      _cut,
      _place('Cu/-/-/-'),
      _paint(QuadColor.blue),
      _cut,
      _place('Cg/-/-/-'),
      _rotate,
      _place('Cb/-/-/-'),
      _rotate,
      _place('Cr/-/-/-'),
    ],
  ),
  Level(
    number: 35,
    name: 'Diagonal Gifts',
    section: 'Preserve',
    brief: 'Two relics on the slant. One slice pockets both.',
    start: _s('Cr/-/-/Cy'),
    goal: _s('Cr/Cb/Cb/Cy'),
    tray: [_s('Cu/-/-/-')],
    colors: const [QuadColor.blue],
    canRotate: true,
    canCut: true,
    solution: [
      _cut,
      _place('-/-/-/Cy'),
      _rotate,
      _rotate,
      _cut,
      _place('Cu/-/-/-'),
      _paint(QuadColor.blue),
      _cut,
      _place('Cb/-/-/-'),
      _rotate,
      _place('Cy/-/-/-'),
      _rotate,
      _place('Cb/-/-/-'),
      _rotate,
      _place('Cr/-/-/-'),
    ],
  ),

  // ── Inlay ──
  // Nested stacks. A finished nest is atomic — bank it, never paint it.
  Level(
    number: 36,
    name: 'Copy the Nest',
    section: 'Inlay',
    brief: 'A finished nest. Twin it far away — leave the first unbrushed.',
    start: _s('Sr+Cb/-/-/-'),
    goal: _s('Sr+Cb/-/-/Sr+Cb'),
    tray: [_s('Cu/-/-/-'), _s('Su/-/-/-')],
    colors: const [QuadColor.red, QuadColor.blue],
    canRotate: true,
    canCut: true,
    solution: [
      _cut,
      _place('Cu/-/-/-'),
      _paint(QuadColor.blue),
      _cut,
      _place('Su/-/-/-'),
      _paint(QuadColor.red),
      _cut,
      _place('Cb/-/-/-'),
      _place('Sr/-/-/-'),
      _rotate,
      _rotate,
      _place('Sr+Cb/-/-/-'),
    ],
  ),
  Level(
    number: 37,
    name: 'Warm Sandwich',
    section: 'Inlay',
    brief: 'Cyan is the quiet middle. Warm the rest elsewhere.',
    start: _s('Cc/-/-/-'),
    goal: _s('-/-/-/Cr+Sy+Cc'),
    tray: [_s('Cu/-/-/-'), _s('Su/-/-/-')],
    colors: const [QuadColor.red, QuadColor.yellow],
    canRotate: true,
    canCut: true,
    solution: [
      _cut,
      _place('Su/-/-/-'),
      _paint(QuadColor.yellow),
      _cut,
      _place('Cu/-/-/-'),
      _paint(QuadColor.red),
      _cut,
      _place('Cc/-/-/-'),
      _place('Sy/-/-/-'),
      _place('Cr/-/-/-'),
      _rotate,
      _rotate,
    ],
  ),
  Level(
    number: 38,
    name: 'Offset Rings',
    section: 'Inlay',
    brief: 'One raw heart, needed twice. Borrow it kindly.',
    start: _s('Cu/-/-/-'),
    goal: _s('Cr+Cu/-/Cb+Cu/-'),
    tray: [_s('Cu/-/-/-')],
    colors: const [QuadColor.red, QuadColor.blue],
    canRotate: true,
    canCut: true,
    solution: [
      _cut,
      _place('Cu/-/-/-'),
      _paint(QuadColor.blue),
      _cut,
      _place('Cu/-/-/-'),
      _paint(QuadColor.red),
      _cut,
      _place('Cu/-/-/-'),
      _place('Cb/-/-/-'),
      _rotate,
      _rotate,
      _rotate,
      _place('Cu/-/-/-'),
      _place('Cr/-/-/-'),
    ],
  ),
  Level(
    number: 39,
    name: 'Steel Halo',
    section: 'Inlay',
    brief: 'A cyan moon, already true. Wrap it; dye the rest off-world.',
    start: _s('Cc/Cc/Cc/Cc'),
    goal: _s('Po+Cc/Po+Cc/Po+Cc/Po+Cc'),
    tray: [_s('Pu/Pu/-/-')],
    colors: const [QuadColor.orange],
    canRotate: true,
    canCut: true,
    solution: [
      _cut,
      _place('Pu/Pu/-/-'),
      _paint(QuadColor.orange),
      _cut,
      _place('Po/Po/-/-'),
      _rotate,
      _rotate,
      _cut,
      _place('Cc/Cc/-/-'),
      _place('-/-/Cc/Cc'),
      _place('Po/Po/-/-'),
      _place('-/-/Po/Po'),
    ],
  ),
  Level(
    number: 40,
    name: 'Split Towers',
    section: 'Inlay',
    brief: 'One tower is a gift. The second palette is workshop work.',
    start: _s('Sr+Cb/-/-/-'),
    goal: _s('Sr+Cb/-/Sy+Cg/-'),
    tray: [_s('Cu/-/-/-'), _s('Su/-/-/-')],
    colors: const [QuadColor.yellow, QuadColor.green],
    canRotate: true,
    canCut: true,
    solution: [
      _cut,
      _place('Cu/-/-/-'),
      _paint(QuadColor.green),
      _cut,
      _place('Su/-/-/-'),
      _paint(QuadColor.yellow),
      _cut,
      _place('Cg/-/-/-'),
      _place('Sy/-/-/-'),
      _rotate,
      _rotate,
      _rotate,
      _place('Sr+Cb/-/-/-'),
    ],
  ),
  Level(
    number: 41,
    name: 'Tricolor Field',
    section: 'Inlay',
    brief: 'Red as the inner ring. Guard the hearth before other weathers.',
    start: _s('Cr/Cr/Cr/Cr'),
    goal: _s('Cp+Cb+Cr/Cp+Cb+Cr/Cp+Cb+Cr/Cp+Cb+Cr'),
    tray: [_s('Cu/Cu/Cu/Cu')],
    colors: const [QuadColor.purple, QuadColor.blue],
    canCut: true,
    solution: [
      _cut,
      _place('Cu/Cu/Cu/Cu'),
      _paint(QuadColor.blue),
      _cut,
      _place('Cu/Cu/Cu/Cu'),
      _paint(QuadColor.purple),
      _cut,
      _place('Cr/Cr/-/-'),
      _place('-/-/Cr/Cr'),
      _place('Cb/Cb/-/-'),
      _place('-/-/Cb/Cb'),
      _place('Cp/Cp/-/-'),
      _place('-/-/Cp/Cp'),
    ],
  ),
  Level(
    number: 42,
    name: 'Blade Walk',
    section: 'Inlay',
    brief: 'An orange pike wants the outer wind. Nest, then wander.',
    start: _s('Po/-/-/-'),
    goal: _s('-/-/Po+Sy+Cc/-'),
    tray: [_s('Cu/-/-/-'), _s('Su/-/-/-')],
    colors: const [QuadColor.yellow, QuadColor.cyan],
    canRotate: true,
    canCut: true,
    solution: [
      _cut,
      _place('Cu/-/-/-'),
      _paint(QuadColor.cyan),
      _cut,
      _place('Su/-/-/-'),
      _paint(QuadColor.yellow),
      _cut,
      _place('Cc/-/-/-'),
      _place('Sy/-/-/-'),
      _place('Po/-/-/-'),
      _rotate,
      _rotate,
      _rotate,
    ],
  ),

  // ── Emblem ──
  // Mixed forms as icons. Gifts still constrain the line.
  Level(
    number: 43,
    name: 'Corsage',
    section: 'Emblem',
    brief: 'A red petal, a blue disc — both already true. Trust them.',
    start: _s('Lr/-/-/Cb'),
    goal: _s('Lr/Sy/Tg/Cb'),
    tray: [_s('Su/-/-/-'), _s('Tu/-/-/-')],
    colors: const [QuadColor.yellow, QuadColor.green],
    canRotate: true,
    canCut: true,
    solution: [
      _cut,
      _place('-/-/-/Cb'),
      _rotate,
      _rotate,
      _cut,
      _place('Su/-/-/-'),
      _paint(QuadColor.yellow),
      _cut,
      _place('Tu/-/-/-'),
      _paint(QuadColor.green),
      _cut,
      _place('Tg/-/-/-'),
      _rotate,
      _place('Cb/-/-/-'),
      _rotate,
      _place('Sy/-/-/-'),
      _rotate,
      _place('Lr/-/-/-'),
    ],
  ),
  Level(
    number: 44,
    name: 'Window',
    section: 'Emblem',
    brief: 'One red pane is set. The other three are still a rumour.',
    start: _s('Cr/-/-/-'),
    goal: _s('Cr/Sy/Tb/Wg'),
    tray: [_s('Su/-/-/-'), _s('Tu/-/-/-'), _s('Wu/-/-/-')],
    colors: const [QuadColor.yellow, QuadColor.blue, QuadColor.green],
    canRotate: true,
    canCut: true,
    solution: [
      _cut,
      _place('Su/-/-/-'),
      _paint(QuadColor.yellow),
      _cut,
      _place('Tu/-/-/-'),
      _paint(QuadColor.blue),
      _cut,
      _place('Wu/-/-/-'),
      _paint(QuadColor.green),
      _cut,
      _place('Tb/-/-/-'),
      _rotate,
      _place('Wg/-/-/-'),
      _rotate,
      _place('Sy/-/-/-'),
      _rotate,
      _place('Cr/-/-/-'),
    ],
  ),
  Level(
    number: 45,
    name: 'Twin Roses',
    section: 'Emblem',
    brief: 'A rose already layered. Twin it; leave the first unbrushed.',
    start: _s('Lm+Lr/-/-/-'),
    goal: _s('Lm+Lr/-/-/Lm+Lr'),
    tray: [_s('Lu/-/-/-')],
    colors: const [QuadColor.magenta, QuadColor.red],
    canRotate: true,
    canCut: true,
    solution: [
      _cut,
      _place('Lu/-/-/-'),
      _paint(QuadColor.red),
      _cut,
      _place('Lu/-/-/-'),
      _paint(QuadColor.magenta),
      _cut,
      _place('Lr/-/-/-'),
      _place('Lm/-/-/-'),
      _rotate,
      _rotate,
      _place('Lm+Lr/-/-/-'),
    ],
  ),
  Level(
    number: 46,
    name: 'Firewheel',
    section: 'Emblem',
    brief: 'A mill already red. The other points learn their colours offstage.',
    start: _s('Wr/-/-/-'),
    goal: _s('Wr/Wo/Wy/Wm'),
    tray: [_s('Wu/-/-/-')],
    colors: const [QuadColor.orange, QuadColor.yellow, QuadColor.magenta],
    canRotate: true,
    canCut: true,
    solution: [
      _cut,
      _place('Wu/-/-/-'),
      _paint(QuadColor.yellow),
      _cut,
      _place('Wu/-/-/-'),
      _paint(QuadColor.orange),
      _cut,
      _place('Wu/-/-/-'),
      _paint(QuadColor.magenta),
      _cut,
      _place('Wy/-/-/-'),
      _rotate,
      _place('Wm/-/-/-'),
      _rotate,
      _place('Wo/-/-/-'),
      _rotate,
      _place('Wr/-/-/-'),
    ],
  ),
  Level(
    number: 47,
    name: 'Solar',
    section: 'Emblem',
    brief: 'Red sun at the centre. Orange, then gold — a late afternoon.',
    start: _s('Cr/Cr/Cr/Cr'),
    goal: _s('Cy+Co+Cr/Cy+Co+Cr/Cy+Co+Cr/Cy+Co+Cr'),
    tray: [_s('Cu/Cu/Cu/Cu')],
    colors: const [QuadColor.yellow, QuadColor.orange],
    canCut: true,
    solution: [
      _cut,
      _place('Cu/Cu/Cu/Cu'),
      _paint(QuadColor.orange),
      _cut,
      _place('Cu/Cu/Cu/Cu'),
      _paint(QuadColor.yellow),
      _cut,
      _place('Cr/Cr/-/-'),
      _place('-/-/Cr/Cr'),
      _place('Co/Co/-/-'),
      _place('-/-/Co/Co'),
      _place('Cy/Cy/-/-'),
      _place('-/-/Cy/Cy'),
    ],
  ),
  Level(
    number: 48,
    name: 'Heraldry',
    section: 'Emblem',
    brief: 'A red tile under every gold star. Guard the ember first.',
    start: _s('Sr/-/-/-'),
    goal: _s('Ty+Sr/Wu+Sb/Ty+Sr/Wu+Sb'),
    tray: [_s('Ty/-/-/-'), _s('Sb/-/-/-'), _s('Wu/-/-/-')],
    canRotate: true,
    canCut: true,
    solution: [
      _cut,
      _place('Sr/-/-/-'),
      _place('Ty/-/-/-'),
      _rotate,
      _place('Sb/-/-/-'),
      _place('Wu/-/-/-'),
      _rotate,
      _place('Sb/-/-/-'),
      _place('Wu/-/-/-'),
      _rotate,
      _place('Sr/-/-/-'),
      _place('Ty/-/-/-'),
    ],
  ),
  Level(
    number: 49,
    name: 'Stained Compass',
    section: 'Emblem',
    brief: 'One cyan seed. Four coloured stars will want it underneath.',
    start: _s('Cc/-/-/-'),
    goal: _s('Tr+Cc/Ty+Cc/Tb+Cc/Tg+Cc'),
    tray: [_s('Tr/-/-/-'), _s('Ty/-/-/-'), _s('Tb/-/-/-'), _s('Tg/-/-/-')],
    canRotate: true,
    canCut: true,
    solution: [
      _cut,
      _place('Cc/-/-/-'),
      _place('Tb/-/-/-'),
      _rotate,
      _place('Cc/-/-/-'),
      _place('Tg/-/-/-'),
      _rotate,
      _place('Cc/-/-/-'),
      _place('Ty/-/-/-'),
      _rotate,
      _place('Cc/-/-/-'),
      _place('Tr/-/-/-'),
    ],
  ),

  // ── Commission ──
  // Long lines. The starting piece is still the constraint that makes the icon.
  Level(
    number: 50,
    name: 'Prism',
    section: 'Commission',
    brief: 'A red blade, already honest. The other three pick dyes offstage.',
    start: _s('Pr/-/-/-'),
    goal: _s('Pr/Po/Py/Pg'),
    tray: [_s('Pu/-/-/-')],
    colors: const [QuadColor.orange, QuadColor.yellow, QuadColor.green],
    canRotate: true,
    canCut: true,
    solution: [
      _cut,
      _place('Pu/-/-/-'),
      _paint(QuadColor.yellow),
      _cut,
      _place('Pu/-/-/-'),
      _paint(QuadColor.orange),
      _cut,
      _place('Pu/-/-/-'),
      _paint(QuadColor.green),
      _cut,
      _place('Py/-/-/-'),
      _rotate,
      _place('Pg/-/-/-'),
      _rotate,
      _place('Po/-/-/-'),
      _rotate,
      _place('Pr/-/-/-'),
    ],
  ),
  Level(
    number: 51,
    name: 'Night Garden',
    section: 'Commission',
    brief: 'A purple bar, already mixed. A magenta clover for a full ring.',
    start: _s('Cp/Cp/-/-'),
    goal: _s('Lm+Cp/Lm+Cp/Lm+Cp/Lm+Cp'),
    tray: [_s('Lu/Lu/-/-')],
    colors: const [QuadColor.magenta],
    canRotate: true,
    canCut: true,
    solution: [
      _cut,
      _place('Lu/Lu/-/-'),
      _paint(QuadColor.magenta),
      _cut,
      _place('Lm/Lm/-/-'),
      _rotate,
      _rotate,
      _cut,
      _place('Cp/Cp/-/-'),
      _rotate,
      _rotate,
      _place('Cp/Cp/-/-'),
      _place('Lm/Lm/-/-'),
      _place('-/-/Lm/Lm'),
    ],
  ),
  Level(
    number: 52,
    name: 'South Star',
    section: 'Commission',
    brief: 'Walk the mill home. Build a gold compass around the quiet.',
    start: _s('Wu/-/-/-'),
    goal: _s('Ty/Ty/Wu/Ty'),
    tray: [_s('Tu/-/-/-')],
    colors: const [QuadColor.yellow],
    canRotate: true,
    canCut: true,
    solution: [
      _rotate,
      _rotate,
      _rotate,
      _cut,
      _place('-/-/Wu/-'),
      _rotate,
      _cut,
      _place('Tu/-/-/-'),
      _paint(QuadColor.yellow),
      _cut,
      _place('Wu/-/-/-'),
      _rotate,
      _place('Ty/-/-/-'),
      _rotate,
      _place('Ty/-/-/-'),
      _rotate,
      _place('Ty/-/-/-'),
    ],
  ),
  Level(
    number: 53,
    name: 'Jewel',
    section: 'Commission',
    brief: 'A four-layer jewel, already cut. Copy the cut, not the brushing.',
    start: _s('Wp+Tb+Sg+Cr/-/-/-'),
    goal: _s('Wp+Tb+Sg+Cr/-/-/Wp+Tb+Sg+Cr'),
    tray: [_s('Cu/-/-/-'), _s('Su/-/-/-'), _s('Tu/-/-/-'), _s('Wu/-/-/-')],
    colors: const [
      QuadColor.red,
      QuadColor.green,
      QuadColor.blue,
      QuadColor.purple,
    ],
    canRotate: true,
    canCut: true,
    solution: [
      _cut,
      _place('Cu/-/-/-'),
      _paint(QuadColor.red),
      _cut,
      _place('Su/-/-/-'),
      _paint(QuadColor.green),
      _cut,
      _place('Tu/-/-/-'),
      _paint(QuadColor.blue),
      _cut,
      _place('Wu/-/-/-'),
      _paint(QuadColor.purple),
      _cut,
      _place('Cr/-/-/-'),
      _place('Sg/-/-/-'),
      _place('Tb/-/-/-'),
      _place('Wp/-/-/-'),
      _rotate,
      _rotate,
      _place('Wp+Tb+Sg+Cr/-/-/-'),
    ],
  ),
  Level(
    number: 54,
    name: 'Quartered',
    section: 'Commission',
    brief:
        'Two gifts on the diagonal. The other forms are still unpainted songs.',
    start: _s('Lr/-/-/Wp'),
    goal: _s('Lr/So/Tb/Wp'),
    tray: [_s('Su/-/-/-'), _s('Tu/-/-/-')],
    colors: const [QuadColor.orange, QuadColor.blue],
    canRotate: true,
    canCut: true,
    solution: [
      _cut,
      _place('-/-/-/Wp'),
      _rotate,
      _rotate,
      _cut,
      _place('Su/-/-/-'),
      _paint(QuadColor.orange),
      _cut,
      _place('Tu/-/-/-'),
      _paint(QuadColor.blue),
      _cut,
      _place('Tb/-/-/-'),
      _rotate,
      _place('Wp/-/-/-'),
      _rotate,
      _place('So/-/-/-'),
      _rotate,
      _place('Lr/-/-/-'),
    ],
  ),
  Level(
    number: 55,
    name: 'Half Dyed',
    section: 'Commission',
    brief: 'Two relics on the slant. Dye one. Leave one wild.',
    start: _s('Tu+Su/-/-/Wu+Cu'),
    goal: _s('Ty+Sr/-/-/Wu+Cu'),
    tray: [_s('Su/-/-/-'), _s('Tu/-/-/-')],
    colors: const [QuadColor.yellow, QuadColor.red],
    canRotate: true,
    canCut: true,
    solution: [
      _cut,
      _place('-/-/-/Wu+Cu'),
      _rotate,
      _rotate,
      _cut,
      _place('Su/-/-/-'),
      _paint(QuadColor.red),
      _cut,
      _place('Tu/-/-/-'),
      _paint(QuadColor.yellow),
      _cut,
      _place('Wu+Cu/-/-/-'),
      _rotate,
      _rotate,
      _place('Sr/-/-/-'),
      _place('Ty/-/-/-'),
    ],
  ),
  Level(
    number: 56,
    name: 'Cabinet',
    section: 'Commission',
    brief: 'The disc on the plate is a heart. Four forms, four weathers.',
    start: _s('Cu/-/-/-'),
    goal: _s('Pr+Cu/Lo/Tm/Wp'),
    tray: [_s('Pu/-/-/-'), _s('Lu/-/-/-'), _s('Tu/-/-/-'), _s('Wu/-/-/-')],
    colors: const [
      QuadColor.red,
      QuadColor.orange,
      QuadColor.magenta,
      QuadColor.purple,
    ],
    canRotate: true,
    canCut: true,
    solution: [
      _cut,
      _place('Pu/-/-/-'),
      _paint(QuadColor.red),
      _cut,
      _place('Lu/-/-/-'),
      _paint(QuadColor.orange),
      _cut,
      _place('Tu/-/-/-'),
      _paint(QuadColor.magenta),
      _cut,
      _place('Wu/-/-/-'),
      _paint(QuadColor.purple),
      _cut,
      _place('Tm/-/-/-'),
      _rotate,
      _place('Wp/-/-/-'),
      _rotate,
      _place('Lo/-/-/-'),
      _rotate,
      _place('Cu/-/-/-'),
      _place('Pr/-/-/-'),
    ],
  ),
];

Level levelByNumber(int number) =>
    kLevels.firstWhere((l) => l.number == number, orElse: () => kLevels.first);

/// Levels grouped by [Level.section], preserving authored order.
List<MapEntry<String, List<Level>>> get kLevelSections {
  final groups = <String, List<Level>>{};
  for (final level in kLevels) {
    groups.putIfAbsent(level.section, () => <Level>[]).add(level);
  }
  return groups.entries.toList(growable: false);
}
