// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/entities.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 696186474022560818),
    name: 'AppPrefs',
    lastPropertyId: const obx_int.IdUid(5, 573261110942141302),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7137979589667332022),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7309739076962000102),
        name: 'muted',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7109747766997957070),
        name: 'confetti',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2411702965578818592),
        name: 'language',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 573261110942141302),
        name: 'targetPreview',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 1183849958889912128),
    name: 'LevelRecord',
    lastPropertyId: const obx_int.IdUid(4, 1561399661379393555),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3272950600892809558),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8182828831994760958),
        name: 'levelNumber',
        type: 6,
        flags: 40,
        indexId: const obx_int.IdUid(1, 4912966184143097217),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4511012842606516898),
        name: 'bestMoves',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1561399661379393555),
        name: 'clears',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 1183849958889912128),
    lastIndexId: const obx_int.IdUid(1, 4912966184143097217),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    AppPrefs: obx_int.EntityDefinition<AppPrefs>(
      model: _entities[0],
      toOneRelations: (AppPrefs object) => [],
      toManyRelations: (AppPrefs object) => {},
      getId: (AppPrefs object) => object.id,
      setId: (AppPrefs object, int id) {
        object.id = id;
      },
      objectToFB: (AppPrefs object, fb.Builder fbb) {
        final confettiOffset = fbb.writeString(object.confetti);
        final languageOffset = fbb.writeString(object.language);
        final targetPreviewOffset = fbb.writeString(object.targetPreview);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addBool(1, object.muted);
        fbb.addOffset(2, confettiOffset);
        fbb.addOffset(3, languageOffset);
        fbb.addOffset(4, targetPreviewOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final mutedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          6,
          false,
        );
        final confettiParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final languageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final targetPreviewParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final object = AppPrefs(
          id: idParam,
          muted: mutedParam,
          confetti: confettiParam,
          language: languageParam,
          targetPreview: targetPreviewParam,
        );

        return object;
      },
    ),
    LevelRecord: obx_int.EntityDefinition<LevelRecord>(
      model: _entities[1],
      toOneRelations: (LevelRecord object) => [],
      toManyRelations: (LevelRecord object) => {},
      getId: (LevelRecord object) => object.id,
      setId: (LevelRecord object, int id) {
        object.id = id;
      },
      objectToFB: (LevelRecord object, fb.Builder fbb) {
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.levelNumber);
        fbb.addInt64(2, object.bestMoves);
        fbb.addInt64(3, object.clears);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final levelNumberParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final bestMovesParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final clearsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final object = LevelRecord(
          id: idParam,
          levelNumber: levelNumberParam,
          bestMoves: bestMovesParam,
          clears: clearsParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AppPrefs] entity fields to define ObjectBox queries.
class AppPrefs_ {
  /// See [AppPrefs.id].
  static final id = obx.QueryIntegerProperty<AppPrefs>(
    _entities[0].properties[0],
  );

  /// See [AppPrefs.muted].
  static final muted = obx.QueryBooleanProperty<AppPrefs>(
    _entities[0].properties[1],
  );

  /// See [AppPrefs.confetti].
  static final confetti = obx.QueryStringProperty<AppPrefs>(
    _entities[0].properties[2],
  );

  /// See [AppPrefs.language].
  static final language = obx.QueryStringProperty<AppPrefs>(
    _entities[0].properties[3],
  );

  /// See [AppPrefs.targetPreview].
  static final targetPreview = obx.QueryStringProperty<AppPrefs>(
    _entities[0].properties[4],
  );
}

/// [LevelRecord] entity fields to define ObjectBox queries.
class LevelRecord_ {
  /// See [LevelRecord.id].
  static final id = obx.QueryIntegerProperty<LevelRecord>(
    _entities[1].properties[0],
  );

  /// See [LevelRecord.levelNumber].
  static final levelNumber = obx.QueryIntegerProperty<LevelRecord>(
    _entities[1].properties[1],
  );

  /// See [LevelRecord.bestMoves].
  static final bestMoves = obx.QueryIntegerProperty<LevelRecord>(
    _entities[1].properties[2],
  );

  /// See [LevelRecord.clears].
  static final clears = obx.QueryIntegerProperty<LevelRecord>(
    _entities[1].properties[3],
  );
}
